version: 2

sources: 
  - name: raw
    schema : gz_raw_data
    description : greenwez raw data source
    tables: 
    - name : sales
      identifier: raw_gz_sales 
      description: greenwez sales / we have all the informations here - orders_id and product_id
      freshness: 
        warn_after:
          count: 90
          period: day
        error_after:
          count: 2000
          period: day
      loaded_at_field: "CAST(date_date as TIMESTAMP)"
      tests:
        - unique:
            column_name : "(orders_id || '-' || pdt_id)"
    - name : product
      identifier : raw_gz_product
      description : greenwez products / for each product ID there is a purchase price
      columns:
        - name: products_id
          description: primary key for this table 
          tests:
          - unique
          - not_null
    - name : ship
      identifier: raw_gz_ship 
      description : for each order_id we have informations regarding shipping
      columns: 
        - name : orders_id
          description: primary key
          tests:
            - unique
            - not_null
    - name : adwords
      identifier : raw_gz_adwords
      description: primary key can either be campaign key or a concatonation between paid_source and campaign_key
      tests: 
        - unique:
            column_name : "(date_date || '-' || campaign_key)"
        - not_null: 
            column_name : "(date_date || '-' || campaign_key)"
    - name: bing
      identifier : raw_gz_bing
      description: primary key can either be campaign key or a concatonation between paid_source and campaign_key
      tests: 
        - unique:
            column_name : "(date_date || '-' || campaign_key)"
        - not_null:
            column_name : "(date_date || '-' || campaign_key)"
    - name : criteo
      identifier : raw_gz_criteo
      description: primary key can either be campaign key or a concatonation between paid_source and campaign_key
      tests: 
        - unique:
            column_name : "(date_date || '-' || campaign_key)"
        - not_null:
            column_name : "(date_date || '-' || campaign_key)"
    - name : facebook
      identifier : raw_gz_facebook
      description: primary key can either be campaign key or a concatonation between paid_source and campaign_key
      tests: 
        - unique:
            column_name : "(date_date || '-' || campaign_key)"
        - not_null:
            column_name : "(date_date || '-' || campaign_key)"
    - name : campaign_days
    identifier : int_campaigns_day


